### ISSUE TITLE
Howto react on socket disconnection

### ISSUE THREAD

**Issue by gianks** [azadkuh/qhttp#15]
Hi,
my application is using a pointer to a serverresponse to serve data coming from various sources but when the clients disconnects the object gets deleted causing a segfault.
How can i intercept the object deletion? Is there any signal emitted before the definitive delete?

Thanks

**Comment by azadkuh** [comment]
- please use `dev` branch instead of `master` (until i merge the new changes back to master)

- `qhttp::server::QHttpResponse` is an `QObject`, so you may want to use [`destroyed()`](http://doc.qt.io/qt-5/qobject.html#destroyed) signal.

- the preferred approach is to use `qhttp::server::QHttpConnection` as it has a `disonnected()` signal. so you will be informed directly if a client disconnects.

**Comment by gianks** [comment]
Thanks, i've used the disconnected() signal with success!
Great job with QHttp, thanks!
